repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: pretty-format-json
    args: [--no-ensure-ascii, --autofix]
    files: |
      (?x)^(
        osdeps/.*\.json
      )
- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black
    args: [--safe, --quiet]
    language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    language_version: python3
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: 'v8.15.0'
  hooks:
  - id: eslint
    files: ^storage_service/static/js/(project|.*directory_picker|file-explorer).js
    args: [--fix]
    additional_dependencies:
    - eslint@7.22.0
    - eslint-config-prettier@8.1.0
    - eslint-plugin-prettier@3.3.1
    - prettier@2.2.1
