# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-02 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0031_rclone_space"),
    ]

    operations = [
        migrations.AddField(
            model_name="rclone",
            name="container",
            field=models.CharField(
                blank=True,
                help_text="Bucket or Container Name",
                max_length=64,
                verbose_name="Bucket or Container Name",
            ),
        ),
    ]
