# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-08-03 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0032_rclone_container"),
    ]

    operations = [
        migrations.AddField(
            model_name="rclone",
            name="remote_name",
            field=models.CharField(
                blank=True,
                help_text="Must match rclone environment variables",
                max_length=64,
                verbose_name="Remote Name",
            ),
        ),
        migrations.AlterField(
            model_name="rclone",
            name="container",
            field=models.CharField(
                blank=True,
                help_text="S3 bucket or object store container name",
                max_length=64,
                verbose_name="Bucket or Container Name",
            ),
        ),
    ]
